--MASV - HO TEN
--THANH VIEN 1: 21120065 - NGUYỄN TRANG MAI HẠNH
--THANH VIEN 2: 21120096 - HỒ CHÂU LONG
--THANH VIEN 3: 21120114 - NGUYỄN TRẦN THIÊN PHÚC
--THANH VIEN 4: 21120253 - HUỲNH QUỐC HUY
--LAB: 03 - NHOM 
--NGAY: 13/4/2024
USE MASTER
GO
IF DB_ID('QLSINHVIEN') IS NOT NULL
	DROP DATABASE QLSINHVIEN
GO
CREATE DATABASE QLSINHVIEN
GO
USE QLSINHVIEN
GO

CREATE TABLE SINHVIEN
(
	MASV NVARCHAR(20),
	HOTEN NVARCHAR(100) NOT NULL,
	NGAYSINH DATETIME,
	DIACHI NVARCHAR(200),
	MALOP VARCHAR(20),
	TENDN NVARCHAR(100) NOT NULL,
	MATKHAU VARBINARY NOT NULL,

	CONSTRAINT PK_SINHVIEN
	PRIMARY KEY(MASV)
)
CREATE TABLE NHANVIEN
(
	MANV VARCHAR(20),
	HOTEN NVARCHAR(100) NOT NULL,
	EMAIL VARCHAR(20),
	LUONG VARBINARY,
	TENDN NVARCHAR(100),
	MATKHAU VARBINARY NOT NULL,

	CONSTRAINT PK_NHANVIEN
	PRIMARY KEY(MANV)
)
CREATE TABLE LOP
(
	MALOP VARCHAR(20),
	TENLOP NVARCHAR(100) NOT NULL,
	MANV VARCHAR(20),

	CONSTRAINT PK_LOP
	PRIMARY KEY(MALOP)
)

ALTER TABLE SINHVIEN
ADD
	CONSTRAINT FK_SINHVIEN_LOP
	FOREIGN KEY(MALOP)
	REFERENCES LOP

ALTER TABLE LOP
ADD 
	CONSTRAINT FK_LOP_NHANVIEN
	FOREIGN KEY(MANV)
	REFERENCES NHANVIEN

