--MASV - HO TEN
--THANH VIEN 1: 21120065 - NGUYỄN TRANG MAI HẠNH
--THANH VIEN 2: 21120096 - HỒ CHÂU LONG
--THANH VIEN 3: 21120114 - NGUYỄN TRẦN THIÊN PHÚC
--THANH VIEN 4: 21120253 - HUỲNH QUỐC HUY
--LAB: 03 - NHOM 
--NGAY: 13/4/2024
USE MASTER
GO
IF DB_ID('QLSINHVIEN') IS NOT NULL
	DROP DATABASE QLSINHVIEN
GO
CREATE DATABASE QLSINHVIEN
GO
USE QLSINHVIEN
GO

CREATE TABLE SINHVIEN
(
	MASV NVARCHAR(20),
	HOTEN NVARCHAR(100) NOT NULL,
	NGAYSINH DATETIME,
	DIACHI NVARCHAR(200),
	MALOP VARCHAR(20),
	TENDN NVARCHAR(100) NOT NULL,
	MATKHAU VARBINARY(MAX) NOT NULL,

	CONSTRAINT PK_SINHVIEN
	PRIMARY KEY(MASV)
)
CREATE TABLE NHANVIEN
(
	MANV VARCHAR(20),
	HOTEN NVARCHAR(100) NOT NULL,
	EMAIL VARCHAR(20),
	LUONG VARBINARY ( MAX),
	TENDN NVARCHAR(100),
	MATKHAU VARBINARY(MAX) NOT NULL,

	CONSTRAINT PK_NHANVIEN
	PRIMARY KEY(MANV)
)
CREATE TABLE LOP
(
	MALOP VARCHAR(20),
	TENLOP NVARCHAR(100) NOT NULL,
	MANV VARCHAR(20),

	CONSTRAINT PK_LOP
	PRIMARY KEY(MALOP)
)

ALTER TABLE SINHVIEN
ADD
	CONSTRAINT FK_SINHVIEN_LOP
	FOREIGN KEY(MALOP)
	REFERENCES LOP

ALTER TABLE LOP
ADD 
	CONSTRAINT FK_LOP_NHANVIEN
	FOREIGN KEY(MANV)
	REFERENCES NHANVIEN

CREATE SYMMETRIC KEY SK_NHANVIEN  
WITH  
    ALGORITHM = AES_256  
    ENCRYPTION BY PASSWORD = '21120253'; 
go



--SELECT * FROM sys.asymmetric_keys
--DROP PROCEDURE IF EXISTS SP_INS_PUBLIC_NHANVIEN
--GO
--===================================================================================

CREATE PROCEDURE SP_INS_PUBLIC_NHANVIEN @MANV VARCHAR(20),@HOTEN NVARCHAR(100),@EMAIL VARCHAR(20),
					@LUONG INT,@TENDN NVARCHAR(100),@MATKHAU VARCHAR(100)

AS  
BEGIN  

	EXEC('CREATE ASYMMETRIC KEY '+@MANV+' WITH ALGORITHM = RSA_2048 ENCRYPTION BY PASSWORD = '''+@MATKHAU+'''')
    INSERT INTO NHANVIEN
    VALUES (@MANV,@HOTEN,@EMAIL,
			ENCRYPTBYASYMKEY(ASYMKEY_ID(@MANV), CONVERT(VARBINARY(max),@LUONG)),
			CONVERT(NVARCHAR,@TENDN),HashBytes('SHA1', @MATKHAU))
	PRINT('CREATE ASYMMETRIC KEY '+@MANV+' WITH ALGORITHM = RSA_2048 ENCRYPTION BY PASSWORD = '''+@MATKHAU+'''')
END  
GO
EXEC SP_INS_PUBLIC_NHANVIEN 'NV01', N'NGUYEN VAN A', 'NVB@', 3000000, 'NV01', 'abcd12'

SELECT * FROM NHANVIEN
GO
--=========================================================================

DROP PROCEDURE IF EXISTS SP_SEL_PUBLIC_NHANVIEN
GO
 
CREATE PROCEDURE SP_SEL_PUBLIC_NHANVIEN @TENDN NVARCHAR(100),@MATKHAU VARCHAR(100)
AS
BEGIN
	SELECT MANV,HOTEN,EMAIL,
	CONVERT(INT, DECRYPTBYASYMKEY(ASYMKEY_ID(MANV), LUONG,CONVERT(NVARCHAR,@MATKHAU))) LUONGCB
	FROM NHANVIEN WHERE CONVERT(NVARCHAR,@TENDN) = TENDN AND MATKHAU = HashBytes('SHA1', @MATKHAU)
END
GO
exec SP_SEL_PUBLIC_NHANVIEN 'NV01', 'abcd12'